### ISSUE TITLE
Dashboard page shows wrong size value

### ISSUE THREAD

**Issue by srcr** [countercept/snake-skin#4]
As you can see in below screenshot the value return is in bytes the UI adds KB 

![Annotation 2020-01-20 181708](https://user-images.githubusercontent.com/1507320/72746007-4fa9ce00-3bb1-11ea-9376-3266c38c6e3d.png)

The summary page shows it correctly

![Annotation 2020-01-20 182006](https://user-images.githubusercontent.com/1507320/72746091-8c75c500-3bb1-11ea-90de-6d79de5ec1c2.png)

**Comment by AlexKornitzer** [comment]
Thanks for the report, this already fixed in the new Snake Skin, which I aim to get live this week, assuming no major bugs appear during our current internal testing.

![image](https://user-images.githubusercontent.com/2750747/72748278-ae217d00-3bae-11ea-945a-ba18c2e6bffd.png)

**Comment by AlexKornitzer** [comment]
Now fixed in master #5
