### ISSUE TITLE
New Snake-skin v2 doesn't render base64 embedded images

### ISSUE THREAD

**Issue by srcr** [countercept/snake-skin#6]
As far as I have been able to test the new markdown engine in snake-skin v2 doesn't display the base64 embedded images any more.

**Comment by AlexKornitzer** [comment]
Just fixed an hour ago, when I brought your scale in and realised I had broken it, does git pulling the latest commit fix this? https://github.com/countercept/snake-skin/commit/6822362285ae536ea7a125a49f519e92e9a60f1f

**Comment by srcr** [comment]
Works like a charm, thanks!
